### ISSUE TITLE
Hit error that TypeError: object of type 'Name' has no len()

### ISSUE THREAD

**Issue by star128** [LayneInNL/py2flows#11]
File "\python\lib\site-packages\py2flows-0.1-py3.7.egg\py2flows\cfg\flows.py", line 381, in visit_Assign
        if ret is not None and len(ret) == 1:
TypeError: object of type 'Name' has no len()

**Comment by Xulei-NL** [comment]
@star128 Wow. I didn't expect one would use this tool. It's a bit like an infant now. But I wonder my latest code didn't have such `if ret is not None and len(ret) == 1:`. Do you use the latest code?

**Comment by Xulei-NL** [comment]
@star128 I do think it works most of the time. In the future, it will be tailored for static analysis.
